### ISSUE TITLE
Standardize ludographies/bilbliographies

### ISSUE THREAD

**Issue by caseyg** [caseyg/knutepunkt2017#1]
sometimes called "ludology", "references", etc.

**Comment by SimonBrind** [comment]
It should be Bibliography and Ludography as two separate sections.  One is for books articles etc and the other for games.

**Comment by Lincsand** [comment]
Don't standarise the titles!
Some articles have Bibliographies, some have Ludos, some have both (These are not interchangeble).
If the articles have both, the Ludography is a subsection of the Bibliography, so always arrange
1. Biblio
2. Ludo
 If there is any other designation, ask me directly.  I might just not have gotten to them yet.

**Comment by Lincsand** [comment]
ALSO:
there is one or two articles that in place of biblio/ludo (or even in addition to) have "Personal communication". This is also a subsection of Bibliography, and a seperate part that dosen't fit under the general biblio or the ludo. 
 
In those places the order is:
Biblio
Personal Communication
Ludo

**Comment by caseyg** [comment]
Thanks for the clarifications and edits! Going to drop these in again now, across the book, and will note any inconsistencies in this thread.

**Comment by caseyg** [comment]
Checklist of what was replaced or n/a (not all have ludos):

- [x] 1	Martine Svanevik	Intro to yesterday section
- [x] 2	Grethe Strand	On the road to Node - Interview with Hanne Grasmo
- [x] 3	Charlie Ashby	All Our Yesterdays
- [x] 4	J. Tuomas Harviainen	A Tale of Knutepunkt Theorycrafting
- [x] 5	OPR - Karete Meland	A Comment on “A Tale of Knutepunkt Theorycrafting”, J. Tuomas Harviainen
- [x] 6	Mike Pohjola	The Classical Roots of larp
- [x] 7	Martine Svanevik	Intro to today section
- [x] 8	Juhana Pettersson	The way larps generate stories
- [x] 9	Hélène Henry	Ludo-Narrative Dissonance and Harmony in Larps
- [x] 10	Alma Elofsson & Mimmi Lundkvist,	Pre-Larp Communication
- [x] 11	Agata Świstak	Keeping volunteers alive
- [x] 12	Tadeu Rodrigues Iuama	Three Roads (of Translation) Not Taken
- [x] 13	Masha Karachun, Zhenja (Yauheni) Karachun, Olga Rudak and Nastassia Sinitsyna	The Workshop Pyramid
- [x] 14	Karete Jacobsen Meland & Simo Järvelä	Beyond Play
- [x] 15	OPR - Grethe Strand 	A Comment on on Järvelä and Jacobsen Meland Beyond play
- [x] 16	OPR - Karete Jacobsen Meland & Simo Järvelä response to Grethe	OPR - Karete Jacobsen Meland & Simo Järvelä response to Grethe
- [x] 17	Harry Harold	Sing In Me, Muse, and Through Me Tell the Story...
- [x] 18	Josefin Westborg and Carl Nordblom 	Do You Want to Play Ball?
- [x] 19	Olga Vorobyeva	Designing for Emotions
- [x] 20	Kaisa Kangas	Playing Others’ Stories
- [x] 21	Mo Holkar	History, Herstory and Theirstory: representation of gender and class in larps with a historical setting'
- [x] 22	Blaz Branc	Body Playground Framework
- [x] 23	Charles Nielsen	Playing in Love
- [x] 24	Monika Weißenfels	Telling Character Stories
- [x] 25	John Shockley	Making Heroes
- [x] 26	Charlie Ashby	Playing Around the Event
- [x] 27	OPR - Matt Pennington	Response to Ashby
- [x] 28	OPR - Charlie Ashby	Response to Matt Pennington
- [x] 29	Shoshana Kessock	The Absence of Disabled Bodies in Larp
- [x] 30	Siri Sandquist	Food for Thought
- [x] 31	Mo Mo O’Brien	YouTube and Larp
- [x] 32	Muriel Algayres	Character-based design and narrative tools in the Frenchstyle Romanesque Larp 
- [x] 33	Charles Nielsen	Loyalty to Character
- [x] 34	OPR - Martine Svanevik	A comment on Charles B. Nielsen’s article “Loyalty to Character”
- [x] 35	OPR - Charles Bo Nielsen	Charles Bo Nielsen reply to Martine Svanevik
- [x] 36	Ian Thomas	Moment-Based Story Design
- [x] 37	Emmylou Laird	Curious Pastimes
- [x] 38	Rob Williams	Will to Live
- [x] 39	Jamie Harper	Context, Context, Context
- [x] 40	Claus Raasted Herløvsen	Larp Tourism
- [x] 41	Evan Torner	Tensions Between Transmedia Fandom and Live-Action Role-Play
- [x] 42	Andrea Giovannucci	Meanwhile in the South The southern way / new Italian Larp design.
- [x] 43	Ian Andrews	Tell Us a Story
- [x] 44	OPR - Simon Brind	Response to “Tell Us A Story”, I. Andrews
- [x] 45	OPR- Ian Andrews Response to Simon Brind	Response to Simon Brind
- [x] 46	Martine Svanevik	Intro to tomorrow section
- [x] 47	Eirik Fatland	Future of Nordic larp
- [x] 48	Christopher Amherst	Larp in the Year 2037
- [x] 49	Eva Wei & Rosalind Göthberg 	Thinking Outside the Blackbox
- [x] 50	Jeppe and Maria Bergmann Hamming	Beyond Playing to Lose and Narrativism
- [x] 51	Lorenzo Trenti	An Invitation to Dance
- [x] 52	Nina Runa Essendrop	larp and art.
- [x] 53	Hanne Grasmo	Larp and I – Till Death Do Us Part

**Comment by caseyg** [comment]
p.129 Strand OPR uses the title "Lectures"?

![screen shot 2017-01-07 at 8 23 59 pm](https://cloud.githubusercontent.com/assets/462020/21746552/3ec0e55a-d517-11e6-9e35-fec6a7755655.png)

See also: https://docs.google.com/document/d/1djyBtmHtzYJE9onxHY5lMhFY-WQAHqiim3pAJO_l-bo/edit

**Comment by caseyg** [comment]
p.131 Meland and Jarvela OPR uses title "References" ?

![screen shot 2017-01-07 at 8 25 10 pm](https://cloud.githubusercontent.com/assets/462020/21746560/819b6116-d517-11e6-8793-02a725d7ad78.png)

https://docs.google.com/document/d/1KllM2SSSdvlq-4pEpCswpcMTAjbhsJBPtmEuoTSft6Y/edit#

**Comment by caseyg** [comment]
Removed subhead "Articles" from p.254 Frenchstyle, bc it might just be referring to the bibliography section?

docs:
![screen shot 2017-01-07 at 9 24 07 pm](https://cloud.githubusercontent.com/assets/462020/21746788/a3884d86-d51f-11e6-96e6-0d52cc3e7f60.png)

indesign:
![screen shot 2017-01-07 at 9 24 01 pm](https://cloud.githubusercontent.com/assets/462020/21746792/aea8ec5c-d51f-11e6-9336-8d095e56b591.png)

**Comment by caseyg** [comment]
p.341 Hamming, Beyond Playing To Lose: heading says "Literature" shouldn't it say Bibliography?

![screen shot 2017-01-07 at 11 45 38 pm](https://cloud.githubusercontent.com/assets/462020/21747399/8ae23436-d533-11e6-95a7-c4cc354c2b23.png)

**Comment by caseyg** [comment]
DONE copy and pasting in all the revised ludos. Phew!

Thanks @Lincsand — and when you get a chance please check out the several comments above. Let me know if you have any followup questions, or feel free to make corrections as you see fit.

Note that all italicized titles in the Ludo/Biblios will need to have the _Citation Title_ Character Style applied, since formatting was lost in the copy-pasting:

![screen shot 2017-01-07 at 11 57 57 pm](https://cloud.githubusercontent.com/assets/462020/21747456/27c2f794-d535-11e6-88d7-411119f5ada9.png)

**Comment by caseyg** [comment]
Considering this fixed!
