### ISSUE TITLE
Yesterday section: Page number inconsistencies

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#109]
On page 72, page numbers go from bottom middle to upper corners.

**Comment by Martinemonster** [comment]
Might be a global issue? Needs to be in the same place despite different styles throughout the whole book for readability.

**Comment by Martinemonster** [comment]
Page numbers need to look the same throughout the book. Global issue.

**Comment by caseyg** [comment]
Closing this. The page numbers change location with respect to the format of the story, but I think it will make much more sense once the layouts are final.

Related issues: #110  #116.
