### ISSUE TITLE
Yesterday: The Road Not Taken - quote pasted in as regular text

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#115]
pg. 58. Look for this text: 
 The two voices contained in the work poetically represent the path taken and the path that could have been. One acts upon the other as a shadow, a memory, an anxiety. It is my hope that the spirit of the poem can also be extended to all levels of decision-making of the piece, especially those pertaining to performance. Contemplate the multitude of options at every moment, take the road less traveled (Mestre, 2014, p. 2).

**Comment by caseyg** [comment]
Fixed, thanks! (Related story: #64)
