### ISSUE TITLE
Pagenumbers

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#116]
Some pages are lacking pagenumbers 
Eks: 27, 57 65 etc.

Also, all sections should have pagenumbers in the same place. 
Remember; they watch for pagenumbers while flipping thought, wich means it has to be at the same spot througout for quick access.

**Comment by caseyg** [comment]
@Lincsand Working on page number consistency, still. 

Our plan right now is that it's consistent with the various book-within-a-book layouts, but not necessarily in the same spot on every page. Let's review before we go to print and see if it's too dysfunctional, or if we can make it make sense :)

It should be easier to use as we finish up our layout passes!

(see also: #110)

**Comment by caseyg** [comment]
Closing this. If there are still issues on Sunday we can address before print. But I think this is much more consistent now.
