### ISSUE TITLE
Picture captions

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#121]
Some places they are marked with colour (??) and some are just standard text, not separated from article text other than the word Caption.  These need to be marked up in a way that they stand out as captions, and be consistent across the board. Colourise them?

**Comment by caseyg** [comment]
@Lincsand The current caption style is slightly-smaller italicized text. The colored captions (#24) are ones that have been marked as missing. Still working on this! Will experiment with maybe using a different font. Should be resolved in our upcoming design passes. (See also: #51)

**Comment by caseyg** [comment]
Closing this, since it was mostly related to the way Martine was flagging captions in color so that I'd catch and format them. Thanks!
