### ISSUE TITLE
Blockquote styles

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#122]
Some longer quotes, and theirs references, have due to formatting, become part of the regular text and just looks like normal paragraphs. This is a problem.   We need to mark these consistently within the book.

RN some are marked by extra spacing, smaller print, " " and italics, some have all, some have some of those tools, but most have none and looks like a normal paragraph.

**Comment by caseyg** [comment]
Agreed, that this should be consistent. Seems partly an issue of different writers handling blockquotes differently, and partly a missing text formatting issue. It's on my radar, as I go through! Will note inconsistencies here, if I have questions.

Related issues: #27 #33  #115 #4

**Comment by caseyg** [comment]
I think this has improved drastically in the proofing and design passes! All of the sub-issues linked above are fixed, so I'm closing this. 

@Lincsand, if there are other specific things to resolve, feel free to create new issues for each, with relevant page #s.
