### ISSUE TITLE
Wei & Göthberg Picture

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#123]
In the article, they have a specific picture they wanted put in, but gave us more pictures if we had room. 
We managed to leave out the one picture they actually needed in relation to the meta teq they are describing (Ghost of the fallen...)

I am guessing we don't have the pagecount to just add the extra picture, but could the picture at the end of the article, be swapped for the picture in their folder marked Img_3300.jpg?  (two girls in masks, behind a person sitting)

**Comment by caseyg** [comment]
Good catch! We'll make sure this image gets in, and I bet we can fit 'em all. 

See also: #100

**Comment by Lincsand** [comment]
Reminder that this picture is still lacking. As previously said, if there's a spacing issue, they'd much rather leave out the picture at the end of the article (p. 351) and have this in instead.

Credits Eva Wei  Captions: Ghost of the fallen friends

**Comment by caseyg** [comment]
Fixed, by moving the images around and adding this image.
