### ISSUE TITLE
Picture p. 109 The workshop pyramid

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#144]
It's way too small. Even in scaled up page view (150%) the text for the picture isn't visible at al. 
at 200% it's barely understandable.

**Comment by Lincsand** [comment]
Is it because it's placed as a footnote?

**Comment by caseyg** [comment]
We're going to fix all these, @Lincsand! Related #65 and #47.

**Comment by caseyg** [comment]
Fixed!
