### ISSUE TITLE
Tomorrow: Larp and Art - missing photo credit

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#150]
pg. 378: photos from “Ziegarnik Effect"

**Comment by caseyg** [comment]
Thanks! Related story: #103

**Comment by caseyg** [comment]
I think I fixed this, lemme know or add a clarification here next time you take a look, @Martinemonster?

**Comment by Martinemonster** [comment]
Fixed.

**Comment by caseyg** [comment]
Thx!
