### ISSUE TITLE
Tomorrow: Larp in the Year 2037 text formatting issues

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#157]
Too much white space between paragraphs makes the whole piece unnecessarily long. :)

**Comment by Martinemonster** [comment]
Also: same footnote issue as elsewhere in the book.

**Comment by Martinemonster** [comment]
First line of new list appearing on the bottom of page on pg. 336 (could be solved by fixing original issue)

**Comment by caseyg** [comment]
Thanks! Still working on this one, design-wise. Will take care of these points as we go. (Related story: #99)

**Comment by caseyg** [comment]
Fixed.
