### ISSUE TITLE
Character Moments: remove some

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#158]
As it stands, College of Wizardry is represented as 43% of all character moments in the book. This looks a bit weird. Could you instead import only the character moments marked in green and yellow from the google sheet? (This way, we might save a few pages too, which is only for the better,right?)

**Comment by caseyg** [comment]
Vic cross-checked with the spreadsheet and we removed one or two from InDesign. We might take a few more out as we go based on those highlights. We can check on this before print — closing for now!
