### ISSUE TITLE
Tomorrow: Replace image in Thinking Outside the Black Box

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#161]
Pg. 351: Replace image with Replace with fallen friends, people with white masks. 

Preferably it fits better on page 353 it show the meta-technique mentioned on p 353 
And the text blocks on 353 354 could use an image. It becomes more readable then.

ghost of the fallen friends, 

And Caption:
Showing the "Ghost of the fallen friends' technique"
Photo Eva Wei

**Comment by caseyg** [comment]
(Related story: #100)

**Comment by caseyg** [comment]
Fixed, by moving the images around and adding this image. (Duplicate issue of #123)
