### ISSUE TITLE
Tomorrow: Missing image caption in Thinking Outside the Black Box

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#162]
pg. 348

**Comment by caseyg** [comment]
(Related story: #100)

**Comment by caseyg** [comment]
Put in text blocks with CAPTION GOES HERE on 359 and 362. Also confirm image credit?

![screen shot 2017-01-13 at 12 59 11 pm](https://cloud.githubusercontent.com/assets/462020/21939973/291e9fb2-d990-11e6-8182-7dcd5d5a65dd.png)

![screen shot 2017-01-13 at 12 59 05 pm](https://cloud.githubusercontent.com/assets/462020/21939969/256d3c16-d990-11e6-8bf6-eb0d0cbc8479.png)

**Comment by Lincsand** [comment]
All the pictures are to be credited Eva Wei, she's the photographer on all of them

**Comment by caseyg** [comment]
Looks like this is fixed now, thanks!
