### ISSUE TITLE
Overall bugs: all sections (mostly image captions)

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#163]
Here is a list of missing image captions and other design issues: https://docs.google.com/document/d/1TSbOf0EZxYrRwJ3AxZ_ee7a0gNYfLHW6bvv0aqShQ_w/edit?usp=sharing

**Comment by caseyg** [comment]
Thanks! Pasting here, as a checklist to go through:

- [ ] ~~~P.10/11 - Missing “YESTERDAY” section header? Also missing author name for the mini-intro.~~~ Gonna resolve this as part of section header design pass.

- [ ] ~~~P.38 - Missing image. Not sure what is intended by the floating text “line drawing” and “curve” on the facing page (39).~~~ remove the text, which was a note to ourselves, the square is intended to stay black

- [ ] ~~~“A Tale of KP Theory Crafting” title repeated on both pages?~~~ we like it repeated! It's a book cover and first page...

- [ ] ~~~P.49-50 - page number (49) obscured by Bibliography box. Also p.50 on the following page.~~~  part of the design!! Overlapping papers. 😸 

- [x] P.97 - page number missing.

- [ ] ~~~P.98. - page numbers shift to top of page header. Possibly this style shift (if desired) should occur at the transition from YESTERDAY section to TODAY section?~~~ part of the design

- [x] P.118 - 121 - page numbers disappear altogether.

- [x] P.165 - slipped text box at the bottom.

- [x] P.168-168 - no caption for image.
- [x] P170 - no caption for image.

- [ ] ~~~P.176 - illustration very small in indistinct.~~~ Agreed, but not sure how to address this?

- [x] P.250-251 - no page numbers

- [x] P.251 - no caption for illustration.
- [x] P.254  - no caption for illustration.

- [x] P.270  - no caption for illustration.
- [x] P.2734  - no caption for illustration.
- [x] P.277  - no caption for illustration. 

- [x] P.283  - no caption for either illustration.

- [x] P.304 - no caption for illustration
- [x] P.305 - mid-page graphic line slices through footnote
- [x] P.307 - no caption for illustration.

- [ ] ~~~P. 326-327 - TOMORROW header has slipped?~~~ working on this as part of section heads

- [x] P.348 - no caption for illustration.
- [x] P.351 - no caption for illustration.
- [x] P.374  - no caption for illustration.

**Comment by caseyg** [comment]
Pretty sure most of these are resolved, but leaving it open for review. Some of the page numbers have shifted by now, but I think all images have captions, or a box awaiting captions.
