### ISSUE TITLE
Today: Laird - Curious pastimes: displaced text 

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#164]
Seems like the whole text has been shifted slightly too far to the right.

**Comment by Martinemonster** [comment]
pg. 276

**Comment by Martinemonster** [comment]
this also makes the text and image look very weird on pg.278

**Comment by Martinemonster** [comment]
Her conclusion appears after her bibliography. see pg. 280.

**Comment by caseyg** [comment]
Fixed. Was a text-reflow issue.
