### ISSUE TITLE
TODAY: too much white space between intro paragraph and main text in The Workshop Pyramid? 

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#166]
pg. 106

**Comment by Martinemonster** [comment]
Also: it's difficult to see paragraph breaks on pg. 106 because of the way the text lies next to the illustration. I love the reverse pyramid shape of the text, but perhaps it's possible to increase the indentation for each new paragraph slightly in this one article, just to make it clear where there's a break?

**Comment by caseyg** [comment]
Good points! Will address. Related article: #65

**Comment by caseyg** [comment]
Fixed!
