### ISSUE TITLE
TODAY: Muriel's article - unnecessary white space pg. 263

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#169]
Whole empty column before the start of the bibliography.

**Comment by caseyg** [comment]
Good point, will make this look better.

Related article: #84

**Comment by caseyg** [comment]
Think I fixed the part of this that was super bad looking. Will keep blank spaces in mind as we do a final design pass.

**Comment by caseyg** [comment]
Fixed.
