### ISSUE TITLE
Missing Ludography!

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#171]
In Raasteds article "Larp Tourism" p. 296-298 the entire Ludography is missing.
The two entries from the biblio is there, but the ludo is missing.

I've C/P'ed it here too:

Ludography
Amantini, Aladino, Arianna Busti et al. Black Friday. Turin, Italy: Terre Spezzate Cronosfera, Chaos League et al. 2014 and 2016

Appl, Filip, Tomáš Dulka and Jan Zeman et al., Hell on Wheels, Humpolec, Czech Republic: Potkani and LARPard, . 2013, 2014 and 2015 (International run) http://howlarp.cz/ 

Berner, Anders Gredal, Claus Raasted and Agata Swistak et. al., Fairweather Manor. Mozna, Poland: Dziobak Studios, Rollespilsfabrikken(DK) and Liveform(PL). 2015  http://www.fmlarp.com/ 

Brown, Maury Elizabeth and Benjamin A. Morrow, New World Magiscola. USA: Learn Larp. 2016 https://magischola.com/ 
Deutsch, Stefan et al.,.Last Voyage of the Demeter. Germany: Operation Brainfuck. 2015

Ericsson, Martin, Bjarke Pedersen and Johanna Koljonen. Inside Hamlet. Copenhagen,Denmark: Odyssé. 2015

Maj, Krzysztof, Bartek Zioło, and Zofia Urszula Kaleta et al., The Witcher School. Mozna, Poland: 5 Żywiołów Agencja artystyczno-eventowa [5 Elements Agency...]. 2015- http://www.5zywiolow.com/witcherschool/ 

Nielsen, Charles Bo, Dracan Dembinski and Claus Raasted Herløvsen et al. College of Wizardry. Poland: Liveform(PL) and Rollespillsfabrikken(DK), 2014-

Pešta, Adam and David František Wagner et al. Legion : Siberian Story. Hvožďany, Czech Republic: Association Rolling. 2015 http://legion.rolling.cz/ 

Raasted, Claus et al., Convention of Thorns. Poland: White Wolf Publishing and Dziobak Larp Studios. 2016

Summanen, Henrik and Thomas Walch et al.,The Monitor Celestra. Sweden: Alternatliv, Bardo and Berättelsefrämjandet. 2013 http://www.alternaliv.se/en/previous#the-monitor-celestra

**Comment by Lincsand** [comment]
Giovannuchi's article "The southern way" p. 318, is also missing it's Ludography. 

Ludography
Chaos League, New Atlantis, Italy: Chaos League. 2014

**Comment by caseyg** [comment]
Fixed, just needs formatting. Thanks!
