### ISSUE TITLE
TODAY: Will to Live missing image captions

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#175]
Two images on pg. 288

**Comment by caseyg** [comment]
I think the article had no captions listed in Google Docs:

![screen shot 2017-01-14 at 3 54 33 am](https://cloud.githubusercontent.com/assets/462020/21953739/55da03ca-da0d-11e6-8284-5092f3e4048a.png)

![screen shot 2017-01-14 at 3 54 37 am](https://cloud.githubusercontent.com/assets/462020/21953740/594b8ff6-da0d-11e6-84ab-13e8ffa1b0c6.png)

But I added a space for an image caption under the laminate illustration, and if you want to fly in a caption for the inline image as well, let me know what it should say, and I can help shuffle things around so it fits. (A bit tricky with the way the text is all flowing right now, but doable.)

![screen shot 2017-01-14 at 3 54 44 am](https://cloud.githubusercontent.com/assets/462020/21953746/7ece77a2-da0d-11e6-80f3-e99e0003128c.png)

**Comment by Lincsand** [comment]
Added captions last night, in the current pdf
Can be closed
