### ISSUE TITLE
TODAY: Body Playground Framework: missing image caption

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#176]
pg. 170.

**Comment by caseyg** [comment]
Added spots for captions here:

![screen shot 2017-01-14 at 4 02 11 am](https://cloud.githubusercontent.com/assets/462020/21953787/43d12a40-da0e-11e6-806e-ebe0a56cbb59.png)

And here:

![screen shot 2017-01-14 at 4 01 01 am](https://cloud.githubusercontent.com/assets/462020/21953780/1abfe72c-da0e-11e6-8aab-850cd3d8387c.png)

**Comment by Lincsand** [comment]
In place, can be closed
