### ISSUE TITLE
snippets background

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#177]
I'm concerned that some of the moments-backgrounds still makes it very hard to read the actuall text.

It's not the issue with all of them, but the ones with still highcontrast blue/white and very busy tiling is making it harder for me, and will (still) make it near impossible to dicsern for people with actual reading issues (or colour blindness)

Edit: I'll update with pg numbers for the ones I am especially worried about)

**Comment by caseyg** [comment]
Fixed.
