### ISSUE TITLE
Snippets pg 201

### ISSUE THREAD

**Issue by Lincsand** [caseyg/knutepunkt2017#181]
There are three different snippets on p. 201 and all of them are lacking text!
It's there, but outside the  workframe and therefore not on the page.

This goes for Claus' Killed Darling and both the character moments on the same page.
They all have more text, out of the frames.

**Comment by caseyg** [comment]
I think this is fixed, can you let me know if it's still a problem in the current PDF @Lincsand, or clarify? Thanks!

**Comment by Lincsand** [comment]
Not a problem anymore! The last pdf does have all the text for all three!
