### ISSUE TITLE
Overall: page numbers appear on different parts of the page

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#183]
And different sizes. this makes it difficult to flip through the book and find what you're looking for. Please choose one place to have the page numbers for all types of content and do it consistently throughout. 

(sorry if this is a duplicate issue. I think I mentioned it before, but I couldn't re-find the issue I made.)

**Comment by caseyg** [comment]
Leaving page numbers within the various formats, so closing this. Thanks!
