### ISSUE TITLE
TODAY- Pre-larp Communication -Missing images

### ISSUE THREAD

**Issue by grethesofie** [caseyg/knutepunkt2017#188]
I left in in the chat but its better to place it here. If its still doable it would be nice to have the images there. The images is in the drive. https://drive.google.com/open?id=0B6musZ_oS24KQXpudmdYTWduNG8

Name of image: 1. Mixing desk of larp with tape
suggested place: p 98

Caption: IIlustration on how you can use the Mixing Desk of Larp to agree on a vision.  Photo: Alma Elofsson

Name of image: 2. Screenshot Facebook  Suit jacket selfie Alma Elofsson
Suggested place p 99

Caption:  Suit jacket selfie. Printscreen: Alma Elofsson

**Comment by caseyg** [comment]
Done!
