### ISSUE TITLE
TODAY - History, Herstory and Theirstory -Missing image

### ISSUE THREAD

**Issue by grethesofie** [caseyg/knutepunkt2017#189]
Add image
Name: Beyond the Barricades Eva Wei 1
 https://drive.google.com/open?id=0B6musZ_oS24KMGF4TXFmSF9ucGc

Caption: A revolutionary woman in _Beyond the Barricades_. 
Photo: Eva Wei
Suggested place: p165 related to the last paragraph in the left column

**Comment by caseyg** [comment]
Done! Thx.
