### ISSUE TITLE
TODAY: Image caption missing, pg. 125

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#190]
Right above header: "STORIES FROM GAME DESIGN"

Should read: Word cloud illustration showing most common words used in responses to the call for stories. Illustration: Harry Harrold

**Comment by Martinemonster** [comment]
Same issue pg. 131. 

Should read: Word cloud illustration showing most common words used to xxx (Simon to input correct text here). Illustration: Harry Harrold.

**Comment by SimonBrind** [comment]
p.131:  Word cloud illustration showing most common words used to describe the reasons given for submitting a story.  Illustration: Harry Harrold

**Comment by caseyg** [comment]
Fixed! Thanks.
