### ISSUE TITLE
Yesterday: Harviainen's article should have faded yellow instead of yellow? (low-priority)

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#193]
Should the background colour in Harviainen's article be like the pages of an old book? If so, it would work better with the image that's in front of the first article in the Yesterday section, rather than a plain yellow background, I think. (But this is small stuff, and should be looked at after everything else is done.)

**Comment by caseyg** [comment]
Not sure it necessarily needs to look like an old book, since it follows the heavy-handed old-book-pages of the Road to Node, but we'll keep tweaking. Gonna close this for now, thx!
