### ISSUE TITLE
pp. 89, Pettersson "[INSERT ORG: HAMLET POINT]"

### ISSUE THREAD

**Issue by caseyg** [caseyg/knutepunkt2017#25]

**Comment by Martinemonster** [comment]
Will get Linn to answer.

**Comment by Lincsand** [comment]
Thats because I haven't done it yet? As noted in the Draft overview sheet (that I keep telling you to look at)

**Comment by caseyg** [comment]
Will be resolved as part of the re-pasting of all ludos, going on in #1. Thanks, both!
