### ISSUE TITLE
p. 289 meanwhile in the south "(Have to set up  ludography and bibliography)"

### ISSUE THREAD

**Issue by caseyg** [caseyg/knutepunkt2017#37]
removed but wanna check that this gets resolved before print 
<img width="246" alt="screen shot 2017-01-03 at 6 34 46 pm" src="https://cloud.githubusercontent.com/assets/462020/21627109/899e806e-d1e3-11e6-9c25-fe649e0b6571.png">

**Comment by Lincsand** [comment]
Just remove the comment.
Be aware, I haven't gotten to the biblio/ludo here yet, so its not standarised yet.

**Comment by caseyg** [comment]
Thanks! About to be resolved as part of re-ludo-pasting in issue #1.
