### ISSUE TITLE
Find-and-replace Swistak with Świstak?

### ISSUE THREAD

**Issue by caseyg** [caseyg/knutepunkt2017#39]

**Comment by SimonBrind** [comment]
The unsupported character is a problem here, because it is a real letter in Polish!  Is it a font related issue?

**Comment by caseyg** [comment]
I don't remember why this was an issue...the font does support the character. 

I see it being inconsistently used in ludographies. Seems like not-the-biggest-deal though, but would it makes sense to change all mentions of Swistak to Świstak?

**Comment by SimonBrind** [comment]
Świstak is the only one I can think of.  I'd like to spell her name right.

**Comment by caseyg** [comment]
Cool making a checklist, for doing a find-and-replace to include the accent, as I go through.

- [x] Frontmatter
- [x] Yesterday
- [x] Today
- [x] Tomorrow
- [x] Backmatter

**Comment by caseyg** [comment]
Done!
