### ISSUE TITLE
Would it make sense to swap 41 "tensions between transmedia..." (Torner) to Tomorrow and 49 "Thinking Outside the Blackbox" (wei gothberg) to Today?

### ISSUE THREAD

**Issue by caseyg** [caseyg/knutepunkt2017#44]

**Comment by SimonBrind** [comment]
They sort of fit in both Today and Tomorrow don't they?  I'm happy to move them into Today, but we'd need to think more about exactly where they fit.

On the whole I'd rather they stayed put.

**Comment by caseyg** [comment]
Cool, will leave as is. Thanks!
