### ISSUE TITLE
Clarify table in "Designing for Emotions" Olga Vorobyeva

### ISSUE THREAD

**Issue by caseyg** [caseyg/knutepunkt2017#46]

**Comment by SimonBrind** [comment]
What clarification is required?

**Comment by caseyg** [comment]
@SimonBrind Do you know what the colors refer to? Yellow vs. orange vs. white? Or why player and character are repeated across every row?

![screen shot 2017-01-07 at 8 38 40 pm](https://cloud.githubusercontent.com/assets/462020/21746630/57613158-d519-11e6-9b24-a386a13f2aea.png)

**Comment by ElinNilsen** [comment]
Ah! I figured it out. I'm sure you can do whatever with the colors when you know what they signify:

**Comment by ElinNilsen** [comment]
But how to explain!
White- > unshared emotion
orange -> source of the emotion
yellow -> emotion because of orange 
So the colors are from light to dark to indicate the source or (level of) impact of the played out emotions. Kind of.

**Comment by ElinNilsen** [comment]
This means that repeating the words character and player makes it visually more intuitive to understand the model. As I said, the colors don't matter, but the going from light to darker matters. (I assume that you will do something with it, but just in case, in the latest PDF I got it's cut in half)

**Comment by caseyg** [comment]
Going to leave as is, but note to self to upload our sketches of trying to revise this!
