### ISSUE TITLE
Cutoff text in Yesterday intro

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#50]
Easy fix: remove one linebreak between the Yesterday header and the quote. But! this might make it look slightly cramped. (this is what I've done right now)

Other possibility: edit text to make it fit. 

Casey: please look and tell me which solution is better. If we choose to remove a linebreak, we will need to do that in Today and Tomorrow as well, for consistency.

**Comment by caseyg** [comment]
We're still working on the design of section-breaks, so this is liable to shift in terms of layout, but I resolved the overset text by removing the linebreak for now. Thanks!
