### ISSUE TITLE
Unnecessary linebreak for footnotes

### ISSUE THREAD

**Issue by Martinemonster** [caseyg/knutepunkt2017#54]
Seems like there's a lot of whitespace between footnotes if there are more than one to a page, see pg 35. Change style to save space? (or there could be a paragraph change there that I'm not seeing, but I couldn't find a way to remove it)

**Comment by caseyg** [comment]
Agreed! This is a layout bug, I'll be able to fix it on my end across the book.

**Comment by caseyg** [comment]
Fixed in:
- [x] Yesterday
- [x] Today
- [x] Tomorrow

**Comment by caseyg** [comment]
Pretty sure this is fixed across the whole book.
